export const swapping= 
 { id:'vm-paging-swapping',
    title: 'Paging & Swapping Mechanics',
    subtopics: [
        { id: 'paging-illusion', title: '1. The Paging Illusion' },
        { id: 'virt-address-cats', title: '2. Virtual Address Categories' },
        { id: 'swapping-mech', title: '3. Swapping & Context Switching' },
        { id: 'fragmentation-deep', title: '4. Fragmentation Problems' }
    ],
    content: {
        'paging-illusion': {
            title: 'The Paging Concept',
            html: `
                <div class="space-y-6">
                    <section class="bg-indigo-500/5 border border-indigo-500/20 p-6 rounded-2xl">
                        <h4 class="text-indigo-400 font-black text-xs uppercase mb-4 tracking-widest underline decoration-indigo-500/30 underline-offset-8">The Complete Copy Illusion</h4>
                        <p class="text-sm text-gray-300 leading-relaxed">
                            To the process, it appears it has its own <strong>complete copy of physical memory</strong> (a private address space). In reality, the OS manages this through a clever "Shell Game":
                        </p>
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
                            <div class="p-4 bg-white/5 border border-white/10 rounded-xl flex items-center gap-3">
                                <div class="text-xl">💾</div>
                                <div class="text-[11px] text-gray-400">Pages not in use are written back to <strong>Secondary Storage (Disk)</strong>.</div>
                            </div>
                            <div class="p-4 bg-white/5 border border-white/10 rounded-xl flex items-center gap-3">
                                <div class="text-xl">🔄</div>
                                <div class="text-[11px] text-gray-400">Memory pages are <strong>swapped in and out on demand</strong>.</div>
                            </div>
                        </div>
                    </section>
                    <div class="warn-box border-emerald-500/50 text-emerald-400">
                        <strong>Goal:</strong> This allows <strong>N</strong> concurrent processes (user and kernel) to execute simultaneously, even if their combined memory needs exceed physical RAM.
                    </div>
                </div>
            `
        },
        'virt-address-cats': {
            title: 'Three Categories of Virtual Addresses',
            html: `
                <div class="space-y-6">
                    <p class="text-sm text-gray-300">Every virtual address generated by the CPU falls into one of three categories based on the Page Table state:</p>
                    
                    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                        <!-- Category 1 -->
                        <div class="bg-emerald-500/10 border border-emerald-500/20 p-4 rounded-xl flex flex-col h-full">
                            <span class="text-xs font-black text-emerald-400 mb-2">1. PHYSICAL HIT</span>
                            <p class="text-[10px] text-gray-400 flex-1">Mapped via the <strong>TLB</strong> or <strong>Page Table</strong>. The data resides in RAM.</p>
                            <div class="mt-4 text-center py-1 bg-emerald-500/20 rounded text-[9px] font-mono">Status: Ready</div>
                        </div>
                        <!-- Category 2 -->
                        <div class="bg-amber-500/10 border border-amber-500/20 p-4 rounded-xl flex flex-col h-full">
                            <span class="text-xs font-black text-amber-400 mb-2">2. PAGE MISS (FAULT)</span>
                            <p class="text-[10px] text-gray-400 flex-1">The page exists but is currently in <strong>Secondary Storage</strong>. Must be swapped in.</p>
                            <div class="mt-4 text-center py-1 bg-amber-500/20 rounded text-[9px] font-mono">Status: Swapping</div>
                        </div>
                        <!-- Category 3 -->
                        <div class="bg-red-500/10 border border-red-500/20 p-4 rounded-xl flex flex-col h-full">
                            <span class="text-xs font-black text-red-400 mb-2">3. NOTHING (INVALID)</span>
                            <p class="text-[10px] text-gray-400 flex-1">An invalid memory address. The process is trying to access memory it doesn't own.</p>
                            <div class="mt-4 text-center py-1 bg-red-500/20 rounded text-[9px] font-mono text-red-300">SEGFAULT</div>
                        </div>
                    </div>
                </div>
            `
        },
        'swapping-mech': {
    title: 'Swapping & Context Switching Mechanics',
    html: `
        <div class="space-y-10">
            <!-- 1. CONCEPTUAL BREAKDOWN -->
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div class="step-card border-indigo-500 bg-indigo-500/5 p-4 rounded-xl">
                    <span class="step-title">The Swapping Mechanism</span>
                    <p class="text-xs text-gray-300 leading-relaxed mb-3">
                        During a <strong>context-switch</strong>, the OS must make room for the next process. Traditionally, this meant moving the entire process to disk.
                    </p>
                    <ul class="text-[10px] text-gray-400 space-y-1 list-disc pl-4">
                        <li>Moves some or all of a process to disk (Secondary Storage).</li>
                        <li>Allows the OS to keep only <strong>active portions</strong> in RAM.</li>
                        <li>Necessary to support more processes than RAM can physically hold.</li>
                    </ul>
                </div>

                <div class="step-card border-emerald-500 bg-emerald-500/5 p-4 rounded-xl">
                    <span class="step-title text-emerald-400">The Transition to Paging</span>
                    <p class="text-xs text-gray-300 leading-relaxed mb-3">
                        Standard swapping of huge segments is slow and leads to fragmentation. To solve this, we need <strong>Finer Grained Control</strong>.
                    </p>
                    <div class="p-2 bg-black/40 rounded border border-emerald-500/30 text-center">
                        <span class="text-[10px] font-black text-emerald-400 uppercase">This is Paging</span>
                        <p class="text-[9px] text-gray-500 italic mt-1">(Implementing Page Replacement Algorithms)</p>
                    </div>
                </div>
            </div>

            <!-- 2. HIGH-FIDELITY MAPPING SCHEMATIC (Slide 27 Replica) -->
            <div class="glass p-8 rounded-3xl border border-white/10 bg-slate-950/50 relative overflow-hidden">
                <h4 class="text-center text-[11px] font-black text-white uppercase tracking-[0.3em] mb-10">Multi-Process Translation Architecture</h4>
                
                <div class="flex flex-col xl:flex-row items-center justify-between gap-4 relative z-10 min-h-[550px]">
                    
                    <!-- PROCESS 1: VIRTUAL SPACE -->
                    <div class="flex flex-col items-center gap-4 w-32 group">
                        <div class="text-center">
                            <h5 class="text-[10px] font-black text-blue-400 uppercase">Process 1</h5>
                            <span class="text-[8px] text-gray-500">Virtual Space</span>
                        </div>
                        <div class="w-full border-2 border-blue-500 bg-white/5 rounded flex flex-col font-bold text-[10px] shadow-[0_0_15px_rgba(59,130,246,0.2)]">
                            <div class="p-2 border-b border-blue-500/30 flex justify-center text-blue-300">Code</div>
                            <div class="p-2 border-b border-blue-500/30 flex justify-center text-blue-300">Data</div>
                            <div class="p-2 border-b border-blue-500/30 flex justify-center text-blue-300">Heap</div>
                            <div class="p-2 flex justify-center text-blue-300">Stack</div>
                        </div>
                    </div>

                    <!-- MAPPING OVALS & WIRING -->
                    <div class="flex-1 relative h-[500px] min-w-[450px]">
                        <svg class="absolute inset-0 w-full h-full overflow-visible" viewBox="0 0 500 500">
                            <!-- TRANSLATION MAP OVALS -->
                            <ellipse cx="120" cy="180" rx="25" ry="90" fill="rgba(6, 182, 212, 0.2)" stroke="#06b6d4" stroke-width="2" stroke-dasharray="5 3" />
                            <ellipse cx="380" cy="180" rx="25" ry="90" fill="rgba(249, 115, 22, 0.2)" stroke="#f97316" stroke-width="2" stroke-dasharray="5 3" />

                            <text x="70" y="300" fill="#06b6d4" font-size="11" font-weight="bold">Page Table 1</text>
                            <text x="330" y="300" fill="#f97316" font-size="11" font-weight="bold">Page Table 2</text>

                            <!-- P1 WIRING (Complex Crossover) -->
                            <g stroke="#3b82f6" stroke-width="1.5" opacity="0.6">
                                <line x1="20" y1="80" x2="230" y2="155" /> <!-- Code 1 -->
                                <line x1="20" y1="110" x2="230" y2="235" /> <!-- Data 1 -->
                                <line x1="20" y1="140" x2="230" y2="115" /> <!-- Heap 1 -->
                                <line x1="20" y1="170" x2="230" y2="75" />  <!-- Stack 1 -->
                            </g>

                            <!-- P2 WIRING (Complex Crossover) -->
                            <g stroke="#f97316" stroke-width="1.5" opacity="0.6">
                                <line x1="480" y1="80" x2="270" y2="35" />  <!-- Data 2 -->
                                <line x1="480" y1="110" x2="270" y2="195" /> <!-- Stack 2 -->
                                <line x1="480" y1="140" x2="270" y2="275" /> <!-- Heap 2 -->
                                <line x1="480" y1="170" x2="270" y2="325" /> <!-- Code 2 -->
                            </g>
                        </svg>

                        <!-- CENTRAL PHYSICAL ADDRESS SPACE -->
                        <div class="absolute left-1/2 top-0 -translate-x-1/2 w-20 border-2 border-white/20 bg-black/60 flex flex-col font-bold text-[8px] text-white overflow-hidden shadow-2xl">
                            <div class="h-8 bg-green-700 flex items-center justify-center border-b border-black">Data 2</div>
                            <div class="h-8 bg-cyan-500 flex items-center justify-center border-b border-black">Stack 1</div>
                            <div class="h-8 bg-indigo-500 flex items-center justify-center border-b border-black">Heap 1</div>
                            <div class="h-8 bg-indigo-600 flex items-center justify-center border-b border-black">Code 1</div>
                            <div class="h-8 bg-green-700 flex items-center justify-center border-b border-black">Stack 2</div>
                            <div class="h-8 bg-indigo-500 flex items-center justify-center border-b border-black">Data 1</div>
                            <div class="h-8 bg-orange-600 flex items-center justify-center border-b border-black">Heap 2</div>
                            <div class="h-8 bg-green-700 flex items-center justify-center border-b border-black">Code 2</div>
                            <!-- OS KERNEL REGION -->
                            <div class="h-8 bg-slate-800 flex items-center justify-center border-b border-white/10">OS code</div>
                            <div class="h-8 bg-slate-800 flex items-center justify-center border-b border-white/10">OS data</div>
                            <div class="h-10 bg-slate-800 flex items-center justify-center text-center leading-tight">OS heap &<br>Stacks</div>
                        </div>
                    </div>

                    <!-- PROCESS 2: VIRTUAL SPACE -->
                    <div class="flex flex-col items-center gap-4 w-32">
                        <div class="text-center">
                            <h5 class="text-[10px] font-black text-orange-400 uppercase">Process 2</h5>
                            <span class="text-[8px] text-gray-500">Virtual Space</span>
                        </div>
                        <div class="w-full border-2 border-orange-500 bg-white/5 rounded flex flex-col font-bold text-[10px] shadow-[0_0_15px_rgba(249,115,22,0.2)]">
                            <div class="p-2 border-b border-orange-500/30 flex justify-center text-orange-300">Code</div>
                            <div class="p-2 border-b border-orange-500/30 flex justify-center text-orange-300">Data</div>
                            <div class="p-2 border-b border-orange-500/30 flex justify-center text-orange-300">Heap</div>
                            <div class="p-2 flex justify-center text-orange-300">Stack</div>
                        </div>
                    </div>
                </div>

                <div class="mt-10 pt-4 border-t border-white/5 text-center">
                    <span class="text-[10px] font-black text-gray-500 uppercase tracking-widest">Physical Address Space</span>
                </div>
            </div>

            <!-- 3. DETAILED LOGIC NOTES -->
            <div class="bg-indigo-500/5 border border-indigo-500/20 p-6 rounded-2xl">
                <h4 class="text-xs font-black text-indigo-300 uppercase mb-4 tracking-widest">Why Finer-Grained Control?</h4>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-8 text-[11px] text-gray-400 leading-relaxed">
                    <p>
                        Standard <strong>Segmentation</strong> requires processes to be contiguous blocks. When you swap them, you leave massive "holes" that are hard to fill. 
                    </p>
                    <p>
                        <strong>Paging</strong> allows the OS to break Process 1 into tiny chunks. It can place P1's Stack at the top of RAM and its Code in the middle, filling gaps that would otherwise be wasted.
                    </p>
                </div>
            </div>
        </div>
    `
},
        'fragmentation-deep': {
    title: 'The Fragmentation Crisis',
    html: `
        <div class="space-y-10">
            <!-- THE CORE CHALLENGE (Slide 28) -->
            <section class="bg-red-500/5 border border-red-500/20 p-6 rounded-2xl">
                <h4 class="text-red-400 font-black text-xs uppercase mb-4 tracking-widest">The Efficiency Paradox</h4>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-8 text-[11px] text-gray-300 leading-relaxed">
                    <div class="space-y-3">
                        <p><strong class="text-white">The Variable Chunk Problem:</strong> Without paging, the OS must find a single, contiguous hole for each process. Since processes are different sizes, the OS spends massive CPU cycles "shuffling" memory just to make things fit.</p>
                        <p><strong class="text-white">Swapping Overhead:</strong> Moving a 2GB process from RAM to a Disk (HDD/SSD) takes seconds. In CPU time, this is an eternity. Doing this frequently causes <strong>Thrashing</strong>.</p>
                    </div>
                    <div class="bg-black/40 p-4 rounded-xl border border-white/5 flex flex-col justify-center">
                        <span class="text-[10px] font-bold text-accent mb-2 uppercase">Why it fails:</span>
                        <ul class="space-y-2 opacity-80">
                            <li>• Inefficient to swap entire process memory.</li>
                            <li>• Memory becomes a "Swiss Cheese" of tiny holes.</li>
                            <li>• Process arrival often blocked despite having enough "total" free RAM.</li>
                        </ul>
                    </div>
                </div>
            </section>

            <!-- FRAGMENTATION VISUALIZER (Slide 29 Deep Dive) -->
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
                
                <!-- EXTERNAL FRAGMENTATION -->
                <div class="glass p-6 rounded-2xl border border-red-500/30 bg-red-500/5">
                    <div class="flex items-center justify-between mb-6">
                        <h5 class="text-xs font-black text-red-400 uppercase tracking-widest">1. External Fragmentation</h5>
                        <span class="text-[9px] bg-red-500/20 px-2 py-0.5 rounded text-red-300">Between Chunks</span>
                    </div>
                    
                    <!-- Visual Representation -->
                    <div class="w-full h-24 bg-black/40 rounded-lg border border-white/10 p-2 flex gap-2 items-center">
                        <div class="w-1/4 h-full bg-indigo-500/40 border border-indigo-400/50 rounded flex items-center justify-center text-[8px]">P1</div>
                        <div class="w-12 h-4 bg-red-500/40 rounded-full animate-pulse flex items-center justify-center text-[7px] font-bold">HOLE</div>
                        <div class="w-1/3 h-full bg-indigo-500/40 border border-indigo-400/50 rounded flex items-center justify-center text-[8px]">P2</div>
                        <div class="w-8 h-4 bg-red-500/40 rounded-full animate-pulse flex items-center justify-center text-[7px] font-bold">HOLE</div>
                    </div>
                    
                    <div class="mt-4 space-y-3">
                        <p class="text-[11px] text-gray-400">Total "Free" gaps are scattered. If a new process needs a block larger than any single hole, the system crashes/hangs even if total free RAM > Process Size.</p>
                        <div class="p-2 bg-black/20 rounded font-mono text-[10px] text-red-300/70">
                            Requirement: Contiguous Memory
                        </div>
                    </div>
                </div>

                <!-- INTERNAL FRAGMENTATION -->
                <div class="glass p-6 rounded-2xl border border-amber-500/30 bg-amber-500/5">
                    <div class="flex items-center justify-between mb-6">
                        <h5 class="text-xs font-black text-amber-400 uppercase tracking-widest">2. Internal Fragmentation</h5>
                        <span class="text-[9px] bg-amber-500/20 px-2 py-0.5 rounded text-amber-300">Inside Chunks</span>
                    </div>

                    <!-- Visual Representation -->
                    <div class="w-full h-24 bg-black/40 rounded-lg border border-white/10 p-2 flex items-center justify-center">
                        <div class="w-full h-full bg-indigo-500/40 border border-indigo-400/50 rounded relative overflow-hidden flex items-center justify-start px-4">
                            <span class="text-[9px] font-bold">Used Data</span>
                            <!-- Wasted space block -->
                            <div class="absolute right-0 top-0 bottom-0 w-1/3 bg-amber-500/30 border-l-2 border-dashed border-amber-400/50 flex items-center justify-center">
                                <span class="text-[7px] font-black text-amber-200 rotate-90">WASTED</span>
                            </div>
                        </div>
                    </div>

                    <div class="mt-4 space-y-3">
                        <p class="text-[11px] text-gray-400">Occurs when memory is allocated in fixed-size slots (like 4KB pages). If a process only needs 1KB, the remaining 3KB is "captured" and unusable by anyone else.</p>
                        <div class="p-2 bg-black/20 rounded font-mono text-[10px] text-amber-300/70">
                            Problem: Over-allocation
                        </div>
                    </div>
                </div>

            </div>

            <!-- THE BIG SOLUTION (Transition to Lecture 3) -->
            <section class="bg-emerald-500/5 border border-emerald-500/20 p-6 rounded-xl">
                <h4 class="text-emerald-400 font-bold mb-4 text-xs uppercase tracking-widest">How Paging Solves This</h4>
                <div class="flex flex-col md:flex-row gap-6">
                    <div class="flex-1 space-y-3">
                        <p class="text-xs text-gray-300 leading-relaxed">
                            Paging eliminates <strong>External Fragmentation</strong> entirely. Because all "holes" (frames) are the same size, any page can fit into any frame. 
                        </p>
                        <p class="text-xs text-gray-300 leading-relaxed">
                            However, Paging <strong>introduces</strong> a small amount of <strong>Internal Fragmentation</strong> (on average, half a page per process).
                        </p>
                    </div>
                    <div class="bg-black/40 p-4 rounded-lg border border-emerald-500/30 flex flex-col justify-center">
                        <div class="flex justify-between gap-4 text-[11px] border-b border-white/10 pb-1 mb-1">
                            <span>Ext Frag</span><span class="text-emerald-400">Fixed ✓</span>
                        </div>
                        <div class="flex justify-between gap-4 text-[11px]">
                            <span>Int Frag</span><span class="text-amber-400">Small Cost ⚠</span>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    `
},
    }
}

