import { TopicModule } from '../types';

export const CURRICULUM: Record<string, TopicModule> = {
  vm2: {
    id: 'vm2',
    title: '1. Virtual Memory II',
    subtopics: [
      { id: 'vm-intro', title: '1. Logical-to-Physical translation Overview' },
      { id: 'vm-base-bounds', title: '2. Contiguous Base & Bounds Translation' },
      { id: 'vm-fragmentation', title: '3. Memory Fragmentation Pitfalls' },
      { id: 'vm-paging-concept', title: '4. Non-Contiguous Paging Principle' }
    ],
    content: {
      'vm-intro': {
        title: 'Virtual to Physical Address Translation',
        explanation: 'In early computing, programs referenced physical system memory addresses directly, which led to crashes if another program wrote to the same region. Virtual Memory decouples program-visible memory (the Logical Address Space) from physical microchip memory (RAM). The operating system, in harmony with the CPU\'s Memory Management Unit (MMU), translates every logical request on-the-fly.',
        mathFormula: '$PA = \\text{MMU}(VA) \\quad \\text{where } VA \\in [0, 2^b - 1], \\, PA \\in [0, \\text{Physical RAM} - 1]$',
        workedExample: {
          inputs: 'Virtual Address space of 32 bits ($2^{32}$ bytes = 4 GB), and physical motherboard RAM of 16 MB ($2^{24}$ bytes).',
          steps: [
            'Determine CPU addressable range: $2^{32}$ distinct locations (0x00000000 to 0xFFFFFFFF).',
            'Determine actual physical host board range: $2^{24}$ distinct locations (0x000000 to 0xFFFFFF).',
            'Observe that $4\\text{ GB}$ of virtual address space exceeds $16\\text{ MB}$ of physical space by a factor of 256.',
            'Thus, an ongoing translation mechanism must point active virtual codes to RAM, and passive virtual pages to Secondary Storage (swap).'
          ],
          answer: 'Virtual space capacity is 4 GB; Physical translation capacity is 16 MB. Decode factor is 256:1.'
        },
        interactivePractice: [
          {
            question: 'Why do we decouple logical virtual addresses from physical RAM addresses?',
            choices: [
              'To speed up CPU clock cycles',
              'To guarantee process isolation, security, and exceed physical capacity limitations',
              'To eliminate the need for secondary storage hard drives entirely',
              'To run assembly source code quicker'
            ],
            correctIndex: 1,
            explanation: 'Isolating processes ensures that program A cannot corrupt program B\'s memory, while allowing the combined processes to use more space than physical RAM through swap files.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'Virtual Machine Cloud Servers',
            scenario: 'Hypervisors on AWS EC2 or Google Cloud assign virtual memory boundaries to separate user nodes, running multi-tenant accounts securely on shared physical RAM boards.'
          }
        ]
      },
      'vm-base-bounds': {
        title: 'Base and Bounds Translation Logic',
        explanation: 'The simplest historic dynamic translation maps each active program into a single, contiguous slot of physical memory. This process is fully managed by two hardware registers: the Base Register (which holds the physical start address) and the Bounds Register (which holds the maximum virtual offset). Every address generated by the program is offset by Base, and screened by Bounds.',
        mathFormula: '$(VA < \\text{Bound}) \\Rightarrow PA = VA + \\text{Base},\\; (VA \\geq \\text{Bound}) \\Rightarrow \\text{Trap (Segmentation Fault)}$',
        workedExample: {
          inputs: 'Process Base Register = 0x01A000, Bounds Register = 0x03FF. Incoming Virtual address to translate = 0x01E0.',
          steps: [
            'Check boundary constraint: Compare incoming Virtual Address ($0x01E0$) with the Bounds ($0x03FF$). Since $0x01E0 < 0x03FF$, the offset is legal.',
            'Perform arithmetic offset: Add the Virtual Address to the Base Register, $0x01A000 + 0x01E0$.',
            'Convert result: $0x01A000 + 0x01E0 = 0x01A1E0$.'
          ],
          answer: 'The physical target address is 0x01A1E0. No security trap is triggered.'
        },
        interactivePractice: [
          {
            question: 'What occurs if an application issues a virtual pointer at $0x0A00$ when the hardware Bounds register is set to $0x0400$?',
            choices: [
              'The memory controller wraps the address around using modulo arithmetic',
              'The translation silently completes with garbage data',
              'The CPU invokes a hardware exception Trap (Segmentation Fault), halting execution',
              'The Base register is automatically incremented'
            ],
            correctIndex: 2,
            explanation: 'Any virtual address equal to or greater than the Bounds register is identified as unauthorized. The MMU immediately traps to the kernel handler, generating a Segmentation Fault.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'Retro Game Consoles & Embedded Controllers',
            scenario: 'Microcontrollers with simple hardware architectures use base/bounds to run a single user application without the overhead of heavy multi-level virtual page tables.'
          }
        ]
      },
      'vm-fragmentation': {
        title: 'Memory Fragmentation Pitfalls',
        explanation: 'When allocating contiguous blocks using standard Base/Bounds, physical memory becomes severely fragmented over time. As processes start, run, and exit, vacant spots (holes) are left interspersed. When a new large process arrives, it may be blocked because none of the individual holes are large enough, even though their cumulative free space is more than sufficient. This is called External Fragmentation. To fix it, OS authors had to switch from contiguous blocks to non-contiguous blocks (Paging).',
        mathFormula: '$\\text{External Fragmentation Waste} = \\sum \\text{Holes} \\quad \\text{where } \\max(\\text{Hole}_i) < \\text{Request Size}$',
        workedExample: {
          inputs: 'System RAM: 16 MB. Free segments: Hole A of 3 MB, Hole B of 2 MB, and Hole C of 2 MB. Total free RAM = 7 MB. A new process requiring 4 MB tries to spawn.',
          steps: [
            'Sum up the total available free memory of the system: $3\\text{ MB} + 2\\text{ MB} + 2\\text{ MB} = 7\\text{ MB}$.',
            'Compare the new incoming allocation request ($4\\text{ MB}$) with the individual free gaps.',
            'Observe that the largest single available hole is Hole A ($3\\text{ MB}$), which is too small.',
            'Confirm that although 7 MB of memory is completely empty, the 4 MB process cannot load because memory is not contiguous.'
          ],
          answer: 'The allocation fails due to External Fragmentation, causing immediate application blocking.'
        },
        interactivePractice: [
          {
            question: 'How does Internal Fragmentation differ from External Fragmentation?',
            choices: [
              'Internal occurs outside standard process partitions',
              'Internal occurs when empty memory is allocated inside fixed-size pages, exposing small amounts of unusable, trapped bytes within blocks',
              'Internal is handled strictly by core storage hard drives',
              'Internal fragmentation only affects 16-bit processor boards'
            ],
            correctIndex: 1,
            explanation: 'Internal fragmentation occurs when fixed allocations (e.g. 4KB frames) over-allocate space for small records (e.g. a 1KB file), wasting the remaining space inside that specific block.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'Dynamic Heap Managers',
            scenario: 'Languages like C/C++ implementing malloc() deal with heap fragmentation. Defragmentation or compaction is needed if contiguous requests can no longer be serviced.'
          }
        ]
      },
      'vm-paging-concept': {
        title: 'The Non-Contiguous Paging Principle',
        explanation: 'Paging completely solves external fragmentation by abandoning the requirement of physical contiguity. Virtual and physical memory are broken down into small, fixed, equal-sized slots. In virtual storage, these blocks are called Pages. In physical RAM, they are called Frames. Any virtual page of a process can be mapped to any physical page frame anywhere in RAM, allowing complete scatter-gather loading.',
        mathFormula: '$\\text{Virtual Address (VA)} \\Rightarrow \\langle \\text{Page Value (VPN)}, \\, \\text{Offset (VPO)} \\rangle \\quad \\text{Page Size} = 2^{\\text{offset bits}}$',
        workedExample: {
          inputs: 'A virtual address space using 32-bit pointers and a fixed page size of 4 KB ($4096 = 2^{12}$ bytes). Translate virtual address 0x00A4F30C to Page/Offset pieces.',
          steps: [
            'Determine offset bits: $\\log_2(4096) = 12$ bits. These 12 bits occupy the lowest indices (0 to 11).',
            'Select Virtual Page Number (VPN) bits: The upper 20 bits ($32 - 12 = 20$ bits).',
            'Split the hex value 0x00A4F30C: Offset occupies the lower 3 hex digits (30C).',
            'The VPN occupies the upper 5 hex digits (00A4F).'
          ],
          answer: 'Virtual Page Number (VPN) = 0x00A4F, Virtual Page Offset (VPO) = 0x30C.'
        },
        interactivePractice: [
          {
            question: 'What is the absolute benefit of Paging compared to Segmented Contiguous allocation?',
            choices: [
              'It removes page tables completely',
              'It eliminates the need for any translation hardware',
              'It eliminates external fragmentation entirely because any free frame can host any page',
              'It reduces physical address width to 8 bits'
            ],
            correctIndex: 2,
            explanation: 'Paging divides memory into equal fixed blocks. Since any free slot can take any page, there is no wasted space between segments, eliminating external fragmentation.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'Standard Desktop Systems',
            scenario: 'Modern operating systems default to 4 KB page frame layouts to easily run thousands of background subtopics and libraries without wasting physically scattered chips.'
          }
        ]
      }
    }
  },
  pgt: {
    id: 'pgt',
    title: '2. Page Tables',
    subtopics: [
      { id: 'pt-translation', title: '1. hardware Translation Logic & Diagrams' },
      { id: 'pt-ptbr', title: '2. PTBR Context Switch Mechanism' },
      { id: 'pt-anatomy', title: '3. PTE Anatomical Metadata bits' },
      { id: 'pt-math', title: '4. Memory Bit Size Calculations' }
    ],
    content: {
      'pt-translation': {
        title: 'CPU Hardware Address Translation Logic',
        explanation: 'When the CPU executes an instruction targeting a virtual address, it extracts the Virtual Page Number (VPN) and the Offset. The VPN acts as an array index into the active process\'s Page Table. The MMU fetches the page table entry, verifies the validation and permission flags, retrieves the Physical Frame Number (PFN / PPN), and appends the VPO. The offset is never changed, because pages and frames are identical in size.',
        mathFormula: '$\\text{Physical Address (PA)} = (\\text{PFN} \\ll \\text{Offset Bits}) \\lor \\text{Offset}$',
        workedExample: {
          inputs: 'A system with 12-bit offset width. Virtual address = 0x0050FF4C. In the translation page table, Entry index 0x0050F contains physical frame number 0x1AC.',
          steps: [
            'Separate Virtual address: Offset = lower 12 bits (3 hex characters) = 0xF4C. Page Number = 0x0050F.',
            'Query the Page Table: Index into offset row 0x0050F and read the physical target frame: 0x1AC.',
            'Combine frame and offset: Concatenate frame 0x1AC with the original offset 0xF4C.',
            'Produce address: 0x1ACF4C.'
          ],
          answer: 'The physical target address is 0x1ACF4C.'
        },
        interactivePractice: [
          {
            question: 'Why is the physical/virtual Offset identical during translation?',
            choices: [
              'Because the CPU prohibits offset modifications to save power',
              'Because pages and frame blocks are defined as identical in size, meaning the location of a byte within a page is the same as inside a physical frame',
              'Because page tables dynamically scale offsets on each clock thread',
              'Because offsets are randomized for security'
            ],
            correctIndex: 1,
            explanation: 'The internal layout of bytes within a physical slot behaves identically to a logical page, so mapping physical frames only requires changing the prefix block.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'GPU Processing units',
            scenario: 'High-performance graphics cards run massive matrix threads using specialized, ultra-fast parallel translation layers to fetch frame buffer textures.'
          }
        ]
      },
      'pt-ptbr': {
        title: 'The Page Table Base Register (PTBR)',
        explanation: 'In physical hardware, there is only one translation MMU pipeline. Since each process has its own isolated, custom page table, the operating system maintains a core CPU hardware configuration known as the Page Table Base Register (PTBR) on x86, which is CR3. The PTBR holds the physical beginning memory pointer of the active process\'s page table. When the kernel context-switches, it simply changes the address in PTBR to register the new process\'s target page table.',
        mathFormula: '$\\text{PTE address calculation} = \\text{PTBR} + (\\text{VPN} \\times \\text{PTE size})$',
        workedExample: {
          inputs: 'Active Page Table pointer = 0x1000, PTE entry width = 4 bytes. Incoming virtual index VPN = 5.',
          steps: [
            'Retrieve the physical base start pointer from PTBR: 0x1000.',
            'Calculate the cell offset: Multiply VPN index (5) by entry width (4 bytes) = 20 bytes (0x14).',
            'Compute final target address: $0x1000 + 0x0014 = 0x1014$.'
          ],
          answer: 'The MMU references address 0x1014 to fetch the translation parameters.'
        },
        interactivePractice: [
          {
            question: 'What register does x86 CPU architecture use to point to the current page directory base?',
            choices: [
              'The EAX accumulator register',
              'The ESP stack pointer register',
              'The CR3 control register (PTBR)',
              'The flag register'
            ],
            correctIndex: 2,
            explanation: 'Control Register 3 (CR3) on x86 architectures points to the physical address of the level-1 page structure, serving as the PTBR.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'Operating System Schedulers',
            scenario: 'When Linux switches context from Process A to Process B, the kernel scheduler executes an instruction to update x86 CR3, instantly isolating the previous address map.'
          }
        ],
        customHtml: `
          <div class="glass-card p-6 rounded-2xl border border-white/10 bg-slate-900/60 my-6">
            <h5 class="text-xs font-black text-indigo-400 uppercase tracking-widest mb-4">Context Switch Logic Flow</h5>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-4 text-center text-xs font-mono">
              <div class="p-3 bg-black/40 border border-white/5 rounded-xl">
                <span class="text-slate-400 block mb-1">1. SUSPEND THREAD</span>
                <p class="text-[11px] text-gray-300">Save CPU Registers of Active Proc A to task stack.</p>
              </div>
              <div class="p-3 bg-indigo-500/20 border border-indigo-500/30 rounded-xl">
                <span class="text-indigo-300 block mb-1">2. RELOAD CR3</span>
                <p class="text-[11px] text-gray-200">Load Proc B page directory pointer into PTBR register.</p>
              </div>
              <div class="p-3 bg-black/40 border border-white/5 rounded-xl">
                <span class="text-slate-400 block mb-1">3. RESUME THREAD</span>
                <p class="text-[11px] text-gray-300">Resume execution using Proc B\'s translation directory.</p>
              </div>
            </div>
          </div>
        `
      },
      'pt-anatomy': {
        title: 'Page Table Entry (PTE) Anatomy',
        explanation: 'A Page Table Entry (PTE) is not just a pointer; it contains essential security, isolation, and status bits monitored directly by the hardware MMU. Understanding these bits is critical to mastering OS security and caching layers.',
        mathFormula: '$\\text{PTE Structure} = \\langle \\text{Physical Page Frame Number (PPN)}, \\, V, \\, D, \\, R, \\, W, \\, X, \\, U/S \\rangle$',
        workedExample: {
          inputs: 'A Page Table Entry with value 0x80004AF1 where bit 0 is Valid, bit 1 is Writeable, and the upper digits denote the PFN.',
          steps: [
            'Inspect the lowest bit (Bit 0): If set, the page is Valid and active in RAM. If unset, it causes a Page Fault.',
            'Inspect the Permission bit (Bit 1): Controls write access permissions.',
            'Verify other attributes: Monitor dirty or reference flags to calculate paging priorities.'
          ],
          answer: 'Bit verification denotes a valid, writeable page targeting frame 0x80004AF.'
        },
        interactivePractice: [
          {
            question: 'What is the function of the "Dirty Bit" (D) in a Page Table Entry?',
            choices: [
              'It flags the page as corrupted or unstable',
              'It notes that the page contents have been modified in RAM, meaning it must be written back to disk before being evicted',
              'It marks the page as readable only by system guest accounts',
              'It indicates execution restrictions'
            ],
            correctIndex: 1,
            explanation: 'The dirty flag signifies write modifications on a loaded page. Pages with dirty bits set must update storage files before eviction, whereas clean pages are evictable instantly.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'Threat-Prevention Systems (W^X / DEP)',
            scenario: 'Security Kernels flag memory buffers (like the input stack) as non-executable (No-Execute NX bit in PTE) to prevent buffer overflows from executing malicious payloads.'
          }
        ]
      },
      'pt-math': {
        title: 'Paging Bit Mathematics',
        explanation: 'To properly configure virtual memory, kernel engineers must calculate the size and physical scaling requirements of process page tables. Let\'s evaluate standard 32-bit architectural constraints.',
        mathFormula: '$\\text{Table Weight} = 2^{\\text{Virtual Pointer Size} - \\log_2(\\text{Page Size})} \\times \\text{PTE Byte Width}$',
        workedExample: {
          inputs: 'A 32-bit virtual architecture using a 4 KB page size, with 4-byte Page Table Entries (PTEs).',
          steps: [
            'Calculate offset size: $\\log_2(4096) = 12$ bits.',
            'Determine VPN bit width: $32 - 12 = 20$ bits.',
            'Compute total page table rows/entries: $2^{20} = 1,048,576$ entries (approximately 1 Million entries).',
            'Compute total RAM space consumed per process: $1,048,576 \\times 4 \\text{ bytes} = 4\\text{ MB}$.'
          ],
          answer: 'The system requires 4 MB of contiguous RAM per running process just to hold its page table.',
        },
        interactivePractice: [
          {
            question: 'If a system has a 64-bit address space, why can\'t we use a simple flat page table?',
            choices: [
              'Because the CPU would overheat translating 64 bits directly',
              'Because a flat table mapping a 64-bit space with 4KB pages would require gigabytes of terabytes of RAM just for the pointers',
              'Because single level structures can only run on 16-bit hardware',
              'Because 64-bit systems do not use offsets'
            ],
            correctIndex: 1,
            explanation: 'With 12 bits of offset, a flat table needs $2^{52}$ entries. Multiplying by 8 bytes per pointer yields petabytes of RAM required just to load the table itself, making hierarchical paging a strict necessity.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'Embedded Systems & IoT Hardware',
            scenario: 'On memory-constrained microcontrollers with only 64KB RAM, system designers map page divisions to 512-byte blocks, keeping allocation structures extremely small.'
          }
        ]
      }
    }
  },
  swa: {
    id: 'swa',
    title: '3. Swapping',
    subtopics: [
      { id: 'swa-illusion', title: '1. The Swap / Page Illusion' },
      { id: 'swa-categories', title: '2. Virtual Address Categories' },
      { id: 'swa-frag-crisis', title: '3. Core Fragmentation crisis' }
    ],
    content: {
      'swa-illusion': {
        title: 'The Swapping and paging Illusion',
        explanation: 'Swapping takes inactive portions of virtual memories (pages) and transfers them to secondary storage (Solid State Drive / Hard Drive file swaps). By copying active pages on-demand to RAM, and offloading unused pages, the operating system gives applications structural access to far more contiguous space than the hardware physically installed.',
        mathFormula: '$\\text{System Memory Capacity} = \\text{motherboard RAM} + \\text{Disk swap space}$',
        workedExample: {
          inputs: 'Motherboard has 8 GB of physical RAM, and the SSD is provisioned with a 16 GB swap file. A data-science Python script tries to load a 12 GB matrix.',
          steps: [
            'The OS detects that the 12 GB file exceeds active RAM (8 GB) by 4 GB.',
            'The kernel offloads 4 GB of background browser tabs, system daemons, and passive frameworks to the SSD swap partition.',
            'This frees up active RAM frames, allowing the 12 GB program to load and map its active pages into physical space.',
            'When those background tabs are selected again, the OS swaps out portion of the active matrix, and reloads the browser tabs from storage.'
          ],
          answer: 'The virtual system successfully hosts a 12 GB program on an 8 GB device using SSD caching.'
        },
        interactivePractice: [
          {
            question: 'What is the performance bottleneck of excessive page swapping (Known as Thrashing)?',
            choices: [
              'The CPU registers fill up too quickly',
              'System performance enters an unstable loop because the CPU spends all of its time reading/writing pages to disk instead of processing program instructions',
              'The motherboard power draw doubles',
              'Files become permanently corrupted'
            ],
            correctIndex: 1,
            explanation: 'When active processes use more memory than what physical RAM can hold, pages are evicted and immediately recalled, resulting in continuous slow disk I/O, which halts operations.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'Mobile Device Memory managers',
            scenario: 'Modern smartphones aggressively suspend background tasks or write cold variables to flash storage files (swap) to maintain absolute layout responsiveness on active targets.'
          }
        ]
      },
      'swa-categories': {
        title: 'Three Categories of Virtual Addresses',
        explanation: 'Every virtual address translation queried by an MMU falls into three distinct logical categories based on current page allocation states. These define how the operating system handles the lifecycle of program pages.',
        mathFormula: '$\\text{Status} = \\begin{cases} \\text{RAM Hit} & \\text{if } V = 1 \\\\ \\text{Page Fault (Disk)} & \\text{if } V = 0 \\, \\& \\, PFN \\ne \\emptyset \\\\ \\text{Segfault (Illegal)} & \\text{if } V = 0 \\, \\& \\, \\text{PFN} = \\emptyset \\end{cases}$',
        workedExample: {
          inputs: 'Virtual addresses: 0x0040 (loaded, valid bit = 1), 0x0110 (stored in swap, valid bit = 0 but has reference), 0x9999 (invalid page address).',
          steps: [
            'First translation (0x0040): Valid bit is 1. The virtual offset is compiled with the active PPN, returning data inside microseconds (RAM Hit).',
            'Second translation (0x0110): Valid bit is 0, but PFN has target records. The MMU raises an exception, the OS interrupt handler pauses the thread, fetches the page from SSD, updates the page entry valid bit to 1, and resumes (Page Fault).',
            'Third translation (0x9999): Valid bit is 0 with no swap sector referenced. The kernel raises a Segmentation Fault and kills the process (Illegal Access).'
          ],
          answer: '0x0040 is a Hit; 0x0110 is a Page Fault; 0x9999 is a Segmentation Fault.'
        },
        interactivePractice: [
          {
            question: 'Which of the following occurs during a standard Page Fault?',
            choices: [
              'The application crashes and restarts',
              'The CPU ignores the page and skips to the next instruction',
              'The OS pauses the process, loads the requested page from disk to RAM, updates the PTE, and retries the instruction',
              'The physical address expands'
            ],
            correctIndex: 2,
            explanation: 'A page fault is a recoverable hardware interrupt. The kernel hooks the fault, copies the block back into an empty frame, and restarts the interrupted CPU command.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'Database Cache Architectures',
            scenario: 'In-memory databases like Redis keep hot keys in fast memory, while cold historical logs are archived to disks, mirroring virtual memory hierarchies.'
          }
        ]
      },
      'swa-frag-crisis': {
        title: 'The Contiguous Fragmentation Crisis',
        explanation: 'In early computing systems that mapped program segments as unbroken physical blocks, fragmentation posed an existential crisis. Standard swapping (copying entire process blocks out to storage) forced the OS to defragment memory through compaction—copying megabytes of active RAM from one side to another. Doing this continually halts user thread execution. This is why Paging is an absolute architectural triumph.',
        mathFormula: '$\\text{External Fragmentation} \\Rightarrow \\text{RAM Swiss Cheese Effect}$',
        workedExample: {
          inputs: 'Motherboard RAM layout: Process A (2MB), Hole (1MB), Process B (2MB), Hole (2MB), Process C (2MB). A new process requiring 3MB contiguous space attempts to launch.',
          steps: [
            'Calculate cumulative free RAM space: $1\\text{ MB} + 2\\text{ MB} = 3\\text{ MB}$.',
            'Attempt to load the new process: There is only a 1MB space or a separate 2MB space.',
            'To load the process contiguous, the OS has to execute Compaction.',
            'Compaction relocates Process B to sit flush with Process A, merging the 1MB and 2MB gaps into a single 3MB contiguous block.'
          ],
          answer: 'Without compaction, loading fails. Copying Process B to close the gap introduces heavy latency, illustrating the layout limits of contiguous allocation.'
        },
        interactivePractice: [
          {
            question: 'Why does Paging completely resolve the contiguous fragmentation crisis?',
            choices: [
              'Because RAM is expanded dynamically by the processor',
              'Because paging decouples memory into equal sections, allowing physical blocks to be scattered anywhere in physical RAM',
              'Because paging disables multi-tasking',
              'Because pages are always stored on hard disks'
            ],
            correctIndex: 1,
            explanation: 'Paging allows memory blocks to be mapped non-contiguously. Since any free slot can host any page, the OS never has to perform compaction to create large contiguous frames.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'Virtual Memory Compaction Algorithms',
            scenario: 'Systems use memory compaction algorithms only for giant pages (HugePages) when running massive hypervisors that require contiguous physical blocks.'
          }
        ]
      }
    }
  },
  sha: {
    id: 'sha',
    title: '4. Sharing & Protection',
    subtopics: [
      { id: 'sha-chunks', title: '1. Page Size & Chunk Selection' },
      { id: 'sha-sharing', title: '2. Memory Sharing Mechanics' },
      { id: 'sha-protection', title: '3. Protection & Permissions Matrix' }
    ],
    content: {
      'sha-chunks': {
        title: 'Page Sizes and Chunk Trade-Offs',
        explanation: 'Sizing page structures is a highly delicate sweet-spot decision. Large page classifications (e.g. HugePages of 2MB or 1GB) reduce the height and memory consumption of page tables, but waste massive columns of memory on small allocations (Internal Fragmentation). Small page mappings (e.g. 512 bytes) make packing extremely tight, but result in monstrously heavy tables that eat up main RAM.',
        mathFormula: '$\\text{Average Internal Waste} = \\frac{\\text{Page Size}}{2} \\quad \\text{per process}$',
        workedExample: {
          inputs: 'A system running 100 process instances. Compare memory overhead of flat page tables using 4 KB pages vs. 2 MB HugePages on a 32-bit architecture.',
          steps: [
            'At 4 KB pages: A flat table is 4 MB per process. $100 \\times 4\\text{ MB} = 400\\text{ MB}$ required just to hold tables.',
            'At 2 MB HugePages: Offset bits = 21. VPN bits = 11. entries = 2048. Table size = $2048 \\times 4 = 8\\text{ KB}$ per process. Total table space for 100 processes is less than 1 MB ($800\\text{ KB}$).',
            'Compute the trade-off: If the average process only consumes 50 KB of memory, a 2 MB frame wastes $2048\\text{ KB} - 50\\text{ KB} \\approx 1.99\\text{ MB}$ in internal fragmentation per process.'
          ],
          answer: '4 KB size tables consume 400 MB of space but minimize memory waste; 2 MB HugePages tables consume less than 1 MB of space but waste 199 MB of space through Internal Fragmentation.'
        },
        interactivePractice: [
          {
            question: 'What is the mathematical consequence of quadrupling the page size from 4KB to 16KB?',
            choices: [
              'The page table size quadruples',
              'The number of virtual page entries decreases by 75%, and the offset pointer bit width increases by 2 bits',
              'Offsets are eliminated',
              'Addresses become non-computable'
            ],
            correctIndex: 1,
            explanation: 'Multiplying page size by 4 increases offset width by 2 bits ($2^{14}$ bytes). This reduces the remaining VPN index width by 2 bits, meaning the number of rows in the page table decreases by 75%.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'Enterprise Database Servers',
            scenario: 'Large database servers like Oracle or PostgreSQL are configured with 2 MB or 1 GB HugePages to minimize TLB caching misses when querying gigabyte scale tables.'
          }
        ]
      },
      'sha-sharing': {
        title: 'Memory Sharing Mechanics',
        explanation: 'Paging makes sharing code blocks and datasets incredibly elegant. For example, if ten processes are instances of the same program (like a web browser or standard system libraries), the OS doesn\'t need to load the program executable code ten times. Instead, it loads one copy of the executable code into RAM, and maps the corresponding virtual code pages of all ten processes to point to those exact same physical frames. To coordinate this safely, the page entries are marked Read-Only.',
        mathFormula: '$\\text{PTE}_A[i].\\text{PFN} = \\text{PTE}_B[j].\\text{PFN} = \\text{Shared Frame Address}$',
        workedExample: {
          inputs: 'Process X and Process Y share a dynamic C library hosted in physical RAM frame 0x4B0.',
          steps: [
            'Let Process X map its logical Page 12 to library frame 0x4B0.',
            'Let Process Y map its logical Page 89 to the exact same frame 0x4B0.',
            'When Process X executes Page 12, it fetches instructions from physical pointer 0x4B0.',
            'When Process Y executes Page 89, it fetches instructions from physical pointer 0x4B0.',
            'The OS configures both page entries as READ-ONLY to ensure neither process can modify the shared library code.'
          ],
          answer: 'Both processes execute shared, read-only code from physical frame 0x4B0, drastically saving physical RAM.'
        },
        interactivePractice: [
          {
            question: 'If Process X and Y share a physical page, what occurs if Process X attempts to write to it when it is marked Read-Only?',
            choices: [
              'Process Y receives the written data immediately',
              'The memory controller creates a silent, duplicate copy',
              'The MMU refuses the instruction, generating a memory protection exception trap',
              'The write succeeds but destroys process memory'
            ],
            correctIndex: 2,
            explanation: 'Any unauthorized write command issued against a Read-Only PTE is blocked at the hardware level by the MMU, raising a protection exception to preserve memory integrity.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'Operating System Shells',
            scenario: 'Copy-On-Write (COW) forks: When spawning a child process, the OS shares all memory frames between parent and child, copying them only if a write occurs, saving CPU cycles.'
          }
        ]
      },
      'sha-protection': {
        title: 'The Protection & Permissions Matrix',
        explanation: 'Paging provides granular security rules at the page level. Each PTE contains permission bits like U/S (User/Supervisor), W (Writeable), and NX (No-Execute). The hardware validates these rules on every single clock cycle. This allows the OS to enforce strict protection matrices to block unauthorized reads, coordinate safe code execution, and restrict user-mode operations from interfering with the kernel.',
        mathFormula: '$\\text{Secure Translate}(VA) = (\\text{Mode} \\ge \\text{PTE.U/S} \\quad \\& \\quad \\text{Access} \\subseteq \\text{PTE.Permissions}) \\Rightarrow PA$',
        workedExample: {
          inputs: 'Active virtual pointer = 0x00F0A3 (User space instruction), PTE contains permission set: Supervisor=YES, Write=YES, Valid=YES.',
          steps: [
            'Review incoming execution mode: User thread (unprivileged).',
            'Inspect PTE permission bits: Supervisor flag is active, meaning the page is exclusive to kernel space.',
            'The hardware immediately blocks translation and halts thread execution.',
            'Observe that even though the page is valid in RAM, user code is denied access.'
          ],
          answer: 'A hardware Supervisor access violations is triggered, trapping execution to the OS kernel.'
        },
        interactivePractice: [
          {
            question: 'What is the purpose of the No-Execute (NX / XD) bit in a Page Table Entry?',
            choices: [
              'To speed up arithmetic processing',
              'To prevent buffer overflow exploits by blocking the CPU from executing instructions located in data pages',
              'To make active RAM frames write-only',
              'To disable hard disk access'
            ],
            correctIndex: 1,
            explanation: 'The NX bit designates standard data regions (like stacks or heaps) as non-executable. If malware attempts a buffer overflow to run code inside a data segment, the CPU traps the command.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'Anti-Virus & Kernel Hardening',
            scenario: 'Modern operating systems write-protect application code segments (using NX and Read-Only PTE flags) to block code injection attacks.'
          }
        ]
      }
    }
  },
  multi: {
    id: 'multi',
    title: '5. Multi-level Page Tables',
    subtopics: [
      { id: 'ml-theory', title: '1. Hierarchical Directory Theory' },
      { id: 'ml-intel-i7', title: '2. Intel Core i7 4-Level Case Study' },
      { id: 'ml-5level', title: '3. Intel 57-bit 5-Level Address translation' },
      { id: 'ml-overhead', title: '4. Memory overhead & Space Savings' }
    ],
    content: {
      'ml-theory': {
        title: 'Hierarchical Directory Theory',
        explanation: 'A flat page table requires an entry for every possible virtual page, even if the address space is mostly empty. Since a typical process uses only a tiny fraction of its 4GB capacity (Code, Heap, Stack are clustered far apart with large gaps between them), flat page tables waste megabytes of RAM on null entries. Multi-level Page Tables solve this by introducing a tree of page tables. If a top-level directory entry is null, the entire sub-table it represents does not need to exist, saving massive amounts of RAM.',
        mathFormula: '$\\text{Space Saving} \\Rightarrow \\text{If } \\text{PDE}[i] = 0 \\Rightarrow \\text{Sub-table } L_2 \\text{ is omitted}$',
        workedExample: {
          inputs: 'A 32-bit architecture with a 2-level page table: 10 bits for Directory, 10 bits for Page Table index, 12 bits for offset. A process uses 1 MB of code at address 0x0, and 1 MB of stack at 0xFFF00000.',
          steps: [
            'Virtual address structure: VPN split into $D_1$ (10 bits) and $D_2$ (10 bits).',
            'Map the code at 0x0: Only 1 Directory Entry ($D_1=0$) is active. This directory entry points to one Level-2 table.',
            'Map the stack at 0xFFF00000: Only 1 Directory Entry ($D_1=1023$) is active, pointing to one other Level-2 table.',
            'The other 1022 directory entries are null, so their Level-2 tables are never created.',
            'Calculate table RAM weight: 1 Level-1 table (4 KB) + 2 Level-2 tables (8 KB) = 12 KB, compared to 4 MB for a flat table!'
          ],
          answer: 'The Hierarchical page table consumes only 12 KB of space, translating to a 99.7% reduction in memory overhead.'
        },
        interactivePractice: [
          {
            question: 'What is the absolute benefit of Hierarchical page tables over single flat structures?',
            choices: [
              'They speed up translation times directly',
              'They save massive physical memory by omitting page tables for empty, unmapped address boundaries',
              'They eliminate the need for an MMU register',
              'They increase virtual address ranges'
            ],
            correctIndex: 1,
            explanation: 'By splitting page tables into directory paths, empty virtual spaces do not require second-level pointer tables, saving massive amounts of RAM.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'Desktop Program Executables',
            scenario: 'Every day desktop software (like paint apps or code editors) uses sparse heap allocations. Multi-level tables ensure each app only consumes kilobytes of RAM for its page entries.'
          }
        ]
      },
      'ml-intel-i7': {
        title: 'Intel Core i7 4-Level Case Study',
        explanation: 'The classic x86-64 CPU architecture implements a 4-level page table structure to support a 48-bit Virtual Address Space of up to 256 Terabytes. The virtual pointer is divided into four 9-bit divisions (PML4, PDPT, PD, PT) and a 12-bit offset. Each PML4 entry manages 512 GB of address space, while each lowest-level page table block manages 2 MB.',
        mathFormula: '$\\text{VA (48-bit)} = \\langle \\text{PML4 (9b)}, \\, \\text{PDPT (9b)}, \\, \\text{PD (9b)}, \\, \\text{PT (9b)}, \\, \\text{Offset (12b)} \\rangle$',
        workedExample: {
          inputs: 'A standard x86-64 system translating address 0x00007FFFF7800000.',
          steps: [
            'Break down the 48-bit address into binary segments.',
            'Extract index PML4: Queries the top folder, covering a 512 GB region.',
            'Extract index PDPT: Points to a 1 GB directory.',
            'Extract index PD: References a 2 MB directory.',
            'Extract index PT: Finds the exact 4KB frame address.',
            'Concatenate the lower 12 bits of VPO directly to physical space.'
          ],
          answer: 'The system queries PML4, PDPT, PD, and PT sequentially to translate the 48-bit virtual address.'
        },
        interactivePractice: [
          {
            question: 'How many page entries fit inside a standard 4KB page table under x86-64, if each PTE is 8 bytes?',
            choices: [
              '1024 entries',
              '512 entries',
              '4096 entries',
              '256 entries'
            ],
            correctIndex: 1,
            explanation: 'Dividing table size (4096 bytes) by entry width (8 bytes) yields exactly 512 entries ($2^9$). This is why each index level on x86-64 utilizes 9 bits select entries.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'Desktop Processor Implementations',
            scenario: 'x86-64 processors use PML4 pointer directories to route logical virtual memory calls instantly to motherboard frames.'
          }
        ],
        customHtml: `
          <div class="glass-card p-6 rounded-2xl border border-white/10 bg-slate-950/70 p-6 my-6 overflow-x-auto">
            <h5 class="text-xs font-black text-emerald-400 uppercase tracking-widest mb-6 text-center">x86-64 (48-bit) Translation Hierarchy Walkthrough</h5>
            <div class="flex flex-col gap-4 min-w-[700px] text-xs font-mono text-center">
              <div class="flex gap-2 border-b border-white/5 pb-2">
                <div class="w-16 bg-slate-800 p-2 text-[10px] text-gray-400">CR3 Register</div>
                <div class="flex-1 flex gap-2">
                  <div class="flex-1 bg-red-500/10 border border-red-500/30 p-2 rounded">PML4 (9b)<br><span class="text-[9px] opacity-70">512 GB Range</span></div>
                  <div class="flex-1 bg-indigo-500/10 border border-indigo-500/30 p-2 rounded">PDPT (9b)<br><span class="text-[9px] opacity-70">1 GB Range</span></div>
                  <div class="flex-1 bg-emerald-500/10 border border-emerald-500/30 p-2 rounded">PD (9b)<br><span class="text-[9px] opacity-70">2 MB Range</span></div>
                  <div class="flex-1 bg-yellow-500/10 border border-yellow-500/30 p-2 rounded">PT (9b)<br><span class="text-[9px] opacity-70">4 KB Range</span></div>
                </div>
                <div class="w-24 bg-white/5 p-2 rounded">Offset (12b)<br><span class="text-[9px] opacity-70">Direct VPO</span></div>
              </div>
            </div>
          </div>
        `
      },
      'ml-5level': {
        title: 'Intel 57-bit 5-Level Address Translation',
        explanation: 'As massive database servers and cloud computing systems scaled beyond 256 Terabytes of RAM, the x86-64 architecture was expanded to support 57-bit Virtual Addressing by adding a fifth translation layer, the PML5 directory. This allows addressing of up to 128 Petabytes of virtual space.',
        mathFormula: '$\\text{VA (57-bit)} = \\langle \\text{PML5 (9b)}, \\, \\text{PML4 (9b)}, \\, \\text{PDPT (9b)}, \\, \\text{PD (9b)}, \\, \\text{PT (9b)}, \\, \\text{Offset (12b)} \\rangle$',
        workedExample: {
          inputs: 'A Xeon server mapping a giant 512 TB in-memory database using a 5-level PML5 structure.',
          steps: [
            'Observe address pointer expansion: Pointers use 57 bits.',
            'PML5 level extracts the highest 9 bits (bits 48 to 56). This points to standard PML4 directories.',
            'PML4 retrieves PDPT, followed by PD and PT.',
            'Observe the massive physical memory capacity: $2^{57} = 128 \\text{ Petabytes}$ of accessible space.'
          ],
          answer: 'The 5-Level structure PML5 successfully translates 57-bit memory coordinates, enabling huge database servers.'
        },
        interactivePractice: [
          {
            question: 'What is the highest-level directory in Intel\'s 57-bit memory translation architecture?',
            choices: [
              'CR3',
              'PML4',
              'PML5',
              'PDPT'
            ],
            correctIndex: 2,
            explanation: 'PML5 (Page Map Level 5) is the topmost page structure introduced on modern processors to scale virtual layouts up to 57 bits.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'Mainframe Supercomputers',
            scenario: 'Massive mainframe arrays and supercomputers use PML5 to perform complex fluid dynamic or physics calculations on massive datasets.'
          }
        ]
      },
      'ml-overhead': {
        title: 'Memory Overhead and Space Savings',
        explanation: 'Multi-level translation introduces a physical memory trade-off. It saves megabytes of RAM by avoiding empty, unmapped rows, but requires multiple sequential memory accesses to translate a single virtual address (e.g. 4 lookups for PML4, 5 for PML5). This is called Translation Overhead. CPUs bypass this slowdown using a specialized hardware cache: the Translation Lookaside Buffer (TLB).',
        mathFormula: '$\\text{Memory Access Overhead} = N + 1 \\quad \\text{where } N = \\text{Number of page table levels}$',
        workedExample: {
          inputs: 'A 4-level PML4 system with no TLB caching cache hits. A program performs 1,000 pointer registers.',
          steps: [
            'For every virtual pointer translated, the CPU must fetch PML4, PDPT, PD, and PT directories.',
            'Each translation requires 4 memory reads just to find the physical frame address, plus 1 read to get the actual data.',
            'Compute total accesses: $1,000 \\times 5 = 5,000$ system memory reads.',
            'Observe speed reduction: This drops CPU translation speeds by 80% unless hardware TLB caches are used.'
          ],
          answer: 'Without a TLB cache, a 4-level translation incurs a 4x delay overhead in memory access cycles.'
        },
        interactivePractice: [
          {
            question: 'How do computer processors solve the access overhead of multi-level page tables?',
            choices: [
              'They bypass RAM lookup using SSD arrays',
              'They utilize a high-speed hardware cache called the Translation Lookaside Buffer (TLB) to cache recent translations',
              'They dynamically reduce physical register speeds',
              'They run all processes as supervisor root threads'
            ],
            correctIndex: 1,
            explanation: 'The TLB is a content-addressable CPU cache that stores valid VPN-to-PFN pairings, letting the processor complete translations in less than a nanosecond on cache hits.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'High-Performance Gaming CPUs',
            scenario: 'Processors like AMD Ryzen with unified 3D-V-Cache implement large, smart TLB tags to ensure games run at high framerates.'
          }
        ]
      }
    }
  },
  algo: {
    id: 'algo',
    title: '6. Page Replacement',
    subtopics: [
      { id: 'algo-fifo', title: '1. FIFO (First In First Out)' },
      { id: 'algo-lru', title: '2. LRU (Least Recently Used)' },
      { id: 'algo-opt', title: '3. OPT (Optimal future Replacement)' },
      { id: 'algo-clock', title: '4. Clock (Second Chance) Algorithm' }
    ],
    content: {
      'algo-fifo': {
        title: 'FIFO (First In First Out) Paging',
        explanation: 'First-In-First-Out is the simplest replacement logic. The OS tracks the order pages were loaded in. When physical RAM is full of page frames and a new page fault occurs, the oldest page in memory is evicted to make room, regardless of how often or recently that page is being accessed.',
        mathFormula: '$\\text{Eviction Target} = \\arg\\min_{i \\in \\text{Frames}} (\\text{LoadTime}_i)$',
        workedExample: {
          inputs: '3 memory frames. Reference string: 7, 0, 1, 2, 0, 3. Trace the page frame queue step-by-step.',
          steps: [
            'Step 1: Load 7 (Fault). Frames: [7, -, -].',
            'Step 2: Load 0 (Fault). Frames: [7, 0, -].',
            'Step 3: Load 1 (Fault). Frames: [7, 0, 1].',
            'Step 4: Load 2 (Fault). 7 was loaded first, so it is evicted. Frames: [2, 0, 1].',
            'Step 5: Load 0 (Hit). Page 0 is already in frame 1. Frames: [2, 0, 1].',
            'Step 6: Load 3 (Fault). 0 was loaded oldest after 7, so it is evicted. Frames: [2, 3, 1].'
          ],
          answer: 'Total Page Faults = 5.'
        },
        interactivePractice: [
          {
            question: 'What is Belady\'s Anomaly in operating systems page replacement?',
            choices: [
              'A security threat associated with dirty pages',
              'An anomaly where assigning MORE physical frames to a process can sometimes result in MORE page faults under FIFO translation',
              'A hardware failure triggered by multiple supervisor reads',
              'An optimization algorithm'
            ],
            correctIndex: 1,
            explanation: 'Under certain reference strings (e.g. 1,2,3,4,1,2,5,1,2,3,4,5), FIFO raises more faults when frames are expanded (e.g. 4 frames raises 10 faults, while 3 frames raises only 9), illustrating its limitation.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'Network Router Package Queues',
            scenario: 'High-speed network routers use FIFO queue buffers to drop the oldest incoming packets first when buffers overflow under heavy traffic spikes.'
          }
        ]
      },
      'algo-lru': {
        title: 'LRU (Least Recently Used) Paging',
        explanation: 'Least Recently Used uses past access history to predict future needs. When a page replacement is needed, the OS evicts the page that has not been accessed for the longest time, assuming it is the least likely to be needed in the near future.',
        mathFormula: '$\\text{Eviction Target} = \\arg\\min_{i \\in \\text{Frames}} (\\text{LastAccessTime}_i)$',
        workedExample: {
          inputs: '3 memory frames. Reference string: 7, 0, 1, 2, 0, 3.',
          steps: [
            'Step 1: Load 7 (Fault). [7, -, -]. Recent order: [7].',
            'Step 2: Load 0 (Fault). [7, 0, -]. Recent order: [0, 7].',
            'Step 3: Load 1 (Fault). [7, 0, 1]. Recent order: [1, 0, 7].',
            'Step 4: Load 2 (Fault). 7 was used longest ago, so it is evicted. [2, 0, 1]. Recent: [2, 1, 0].',
            'Step 5: Load 0 (Hit). 0 is accessed. [2, 0, 1]. Recent order: [0, 2, 1].',
            'Step 6: Load 3 (Fault). 1 was used longest ago, so it is evicted. [2, 0, 3]. Recent: [3, 0, 2].'
          ],
          answer: 'Total Page Faults = 5.'
        },
        interactivePractice: [
          {
            question: 'Why is LRU typically preferred over FIFO for active workloads?',
            choices: [
              'Because it consumes less computational power in basic chips',
              'Because it respects the Principle of Locality, protecting recently accessed pages from eviction',
              'Because it requires no translation bits',
              'Because it runs completely offline'
            ],
            correctIndex: 1,
            explanation: 'The Principle of Locality states that recently accessed pages are highly likely to be reused soon. LRU directly leverages this to keep "hot" pages in memory, reducing page faults.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'Database Connection Pools',
            scenario: 'Application servers hold active background clients using LRU eviction, closing idle database connections first to free up system sockets.'
          }
        ]
      },
      'algo-opt': {
        title: 'OPT (Optimal Replacement) Paging',
        explanation: 'Optional Replacement (also known as MIN or Belady\'s Optimal Algorithm) is the gold standard benchmark. It has perfect knowledge of the future and always evicts the page that will not be accessed for the longest time in the future. Although impossible to implement in a real OS (since we cannot predict future instructions), it acts as an absolute theoretical benchmark to evaluate other algorithms.',
        mathFormula: '$\\text{Eviction Target} = \\arg\\max_{i \\in \\text{Frames}} (\\text{NextAccessTime}_i)$',
        workedExample: {
          inputs: '3 frames. Reference string: 7, 0, 1, 2, 0, 3, 0, 4.',
          steps: [
            'Step 1: Paging 7 (Fault). [7, -, -].',
            'Step 2: Paging 0 (Fault). [7, 0, -].',
            'Step 3: Paging 1 (Fault). [7, 0, 1].',
            'Step 4: Paging 2 (Fault). We check future uses of {7, 0, 1}. 0 is used at step 5. 7 and 1 are never used again (\\infty). By FIFO tie-breaker, oldest loaded page 7 is evicted. [2, 0, 1].',
            'Step 5: Paging 0 (Hit). [2, 0, 1].',
            'Step 6: Paging 3 (Fault). Check future of {2, 0, 1}: 0 at step 7. 2 and 1 are never used. Evict 1. [2, 0, 3].',
            'Step 7: Paging 0 (Hit). [2, 0, 3].',
            'Step 8: Paging 4 (Fault). [4, 0, 3].'
          ],
          answer: 'Total Page Faults = 6.'
        },
        interactivePractice: [
          {
            question: 'Why is the Optimal (OPT) page replacement algorithm impossible to implement in practice?',
            choices: [
              'Because the CPU would consume too much power tracking physical registers',
              'Because it requires the operating system to have perfect knowledge of all future memory references, which is impossible in general-purpose computing',
              'Because it is restricted to 32-bit platforms',
              'Because pages cannot fit'
            ],
            correctIndex: 1,
            explanation: 'General purpose operating systems cannot know which memory addresses a user will access next (since programs code has conditional branches, user inputs, and interrupts), making OPT purely useful as a theoretical benchmark.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'Simulation & Academic Research',
            scenario: 'Hardware architects capture system call traces of heavy game engines or servers, analyzing how close realistic algorithms (like LRU or Clock) get to the absolute OPT benchmark.'
          }
        ]
      },
      'algo-clock': {
        title: 'Clock (Second Chance) Algorithm',
        explanation: 'Since LRU requires the CPU to update timestamps or move nodes on every single memory access, it is too expensive to implement directly in hardware. The Clock Algorithm approximates LRU with practically zero overhead. It treats physical memory frames as a circular list (like a clock face). Each frame has a single Reference Bit set to 1 by the MMU on any page hit. When eviction is needed, a clock hand sweeps. If a page\'s bit is 1, it gets a "second chance"—its bit is cleared to 0, and the hand advances. The first page with a bit of 0 is evicted.',
        mathFormula: '$\\text{Bit Actions} \\Rightarrow \\begin{cases} \\text{Page Hit} & \\Rightarrow \\text{Set Ref Bit} = 1 \\\\ \\text{Sweep Hand} & \\Rightarrow \\text{If Ref Bit} = 1 \\Rightarrow \\text{Reset to } 0 \\text{ and Advance} \\\\ \\text{Sweep Hand} & \\Rightarrow \\text{If Ref Bit} = 0 \\Rightarrow \\text{Evict page} \\end{cases}$',
        workedExample: {
          inputs: '3 frames. Reference string: 0, 4, 1, 4, 2.',
          steps: [
            'Step 1: Load 0 (Fault). Frames: [0(ref:1), -, -]. Hand at frame 1.',
            'Step 2: Load 4 (Fault). Frames: [0(ref:1), 4(ref:1), -]. Hand at frame 2.',
            'Step 3: Load 1 (Fault). Frames: [0(ref:1), 4(ref:1), 1(ref:1)]. circular list is full. Hand wraps to 0.',
            'Step 4: Load 4 (Hit). 4 is already loaded; set its reference bit to 1. [0(ref:1), 4(ref:1), 1(ref:1)]. Hand stays at 0.',
            'Step 5: Load 2 (Fault). Clock hand sweeps: Frame 0 has bit 1. Reset to 0, advance hand. Frame 1 has bit 1. Reset to 0, advance hand. Frame 2 has bit 1. Reset to 0, advance hand. Hand sweeps back to Frame 0 (now has bit 0). Evict 0. Frames: [2(ref:1), 4(ref:0), 1(ref:0)]. Hand advances to 1.'
          ],
          answer: 'Total Page Faults = 4.'
        },
        interactivePractice: [
          {
            question: 'What is the sweep hand representation in the Clock replacement algorithm?',
            choices: [
              'A software timer checking page ages',
              'A hardware register or variable tracking the next physical frame index to evaluate of eviction',
              'An address pointer to the disk swap partition',
              'A cache directory tag code'
            ],
            correctIndex: 1,
            explanation: 'The clock hand is a simple index pointer that cycles through physical frame positions, checking and updating reference bits in loop fashion.'
          }
        ],
        realWorldApplications: [
          {
            domain: 'OS Kernel Memory Managers (Linux/FreeBSD)',
            scenario: 'The Linux active page eviction daemon (kswapd) implements a hybrid Clock variant to continually scavenge physical slots without throttling active application process threads.'
          }
        ]
      }
    }
  }
};
